default:
  genome: "annotation/GRCh37.p13.genome.fa.bgz"
  global_size: 14
  ann_dir: "annotation"
  datadir: "data"
  resultdir: "results"
  plotdir: "plots"
  scriptdir: "scripts"
  Rlibdir: "R_libraries"

#  threads: 4

## to activate alternative environment: `Sys.setenv(R_CONFIG_ACTIVE = "old_DE")`
old_DE:
  resultdir: "results_oldDEMaxTC"
  plotdir: "plots_oldDEMaxTC"

